### ISSUE TITLE
Error decoding struct

### ISSUE THREAD

**Issue by frm** [poanetwork/ex_abi#120]
```elixir
iex(17)> ABI.TypeDecoder.decode(r, s, :output)
    ** (MatchError) no match of right hand side value: "0000000000000000000000001429d3e6d95c7a4ad947523784f6290409b0886b000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000183307f698000000000000000000000000000000000000000000000000000000183307f69800000000000000000000000000000000000000000000000000000000000000042697066733a2f2f6261666b726569686c346369367833767470796b32736a3674746b7674643669706b756664756d756e68646e3233676a7332656f616470336b7375000000000000000000000000000000000000000000000000000000000000"
    (ex_abi 0.5.16) lib/abi/type_decoder.ex:351: ABI.TypeDecoder.decode_type/3
    (ex_abi 0.5.16) lib/abi/type_decoder.ex:188: anonymous fn/3 in ABI.TypeDecoder.do_decode_raw/2
    (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_abi 0.5.16) lib/abi/type_decoder.ex:185: ABI.TypeDecoder.do_decode_raw/2
    (ex_abi 0.5.16) lib/abi/type_decoder.ex:179: ABI.TypeDecoder.decode_raw/2
```

The example is of a struct with four fields of type `address`, `bytes`, `uint256` and `uint256`:

```solidity
struct Contribution {
    address owner;
    bytes detailsUri;
    uint256 dateOfSubmission;
    uint256 dateOfEngagement;
}

mapping(uint256 => Contribution) public contributions;
```

When calling `constructions`, it errors decoding the output. The response string is correctly built. As an example, using the following output: 

```elixir
"0000000000000000000000001429d3e6d95c7a4ad947523784f6290409b0886b000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000183307f698000000000000000000000000000000000000000000000000000000183307f69800000000000000000000000000000000000000000000000000000000000000042697066733a2f2f6261666b726569686c346369367833767470796b32736a3674746b7674643669706b756664756d756e68646e3233676a7332656f616470336b7375000000000000000000000000000000000000000000000000000000000000"
```

I get the error above when decoding through the lib, while decoding through an online decoder like [this one](https://www.moesif.com/solidity-abi-hex-decoder/decode) I get the right values.

From what I could gather, it's due to a bad offset. [In `type_decoder.ex`](https://github.com/poanetwork/ex_abi/blob/master/lib/abi/type_decoder.ex#L349-L354):

```elixir
  defp decode_type(:bytes, data, full_data) do
    {offset, rest} = decode_uint(data, 256)
    <<_padding::binary-size(offset), rest_data::binary>> = full_data
    {byte_size, dynamic_length_data} = decode_uint(rest_data, 256)
    decode_bytes(dynamic_length_data, byte_size, :right, rest)
  end
```

From a quick look, the value of `offset` does not match the actual offset, causing the match with `full_data` to fail - although I wasn't able to look deep into the reasons for it.

**Comment by frm** [comment]
For context: I'm using the latest version, `0.5.16`

**Comment by frm** [comment]
Found the issue, I didn't notice I had to run `Base.decode16!/2` on the response. Apologies
