### ISSUE TITLE
Mix complile fails on windows

### ISSUE THREAD

**Issue by abdul-playlogix** [poanetwork/ex_abi#20]
Get the following error when trying to compile on windows 10:

```
D:\ex_abi_test>mix compile
==> libsecp256k1
could not compile dependency :libsecp256k1, "mix compile" failed. You can recompile this dependency with "mix deps.compile libsecp256k1", update it with "mix deps.update libsecp256k1" or clean it with "mix deps.clean libsecp256k1"
** (ErlangError) Erlang error: :enoent
    (elixir) lib/system.ex:632: System.cmd("make", [], [into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    d:/Workspaces/Project/Trixta/other/ex_abi/deps/libsecp256k1/mix.exs:3: Mix.Tasks.Compile.MakeBindings.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:68: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:52: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:23: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:39: Mix.Tasks.Compile.All.with_logger_app/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3mix compile
```

Erlang/OTP 21 [erts-10.2] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.7.1 (compiled with Erlang/OTP 19)

**Comment by vbaranov** [comment]
@abdul-playlogix Try the latest update from the master branch and compile with Elixir 1.9.x, Erlang/OTP 22. I am closing this since much time passed from issue creating. If you will still experience this issue, please reopen it.
