### ISSUE TITLE
Problem when parsing tuples and bool

### ISSUE THREAD

**Issue by spapas** [poanetwork/ex_abi#79]
Hello, I've got a contract with the following view:

```
    function getVoteInfo() public view returns (bool, address, string memory, string memory, string memory, string memory, uint) {
        bool isActive = bool(block.timestamp < finishTime);
        return (isActive, voteFrom, question, choice_a, choice_b, choice_c, finishTime);
    }
```

I am trying to call this function using something like 
```
{:ok, is_active, vote_from, question, a, b, c, finish_on} = ExW3.Contract.call(:Voter, :getVoteInfo)
```

When the isActive is false it works fine. However, when it is true I get the following exception:

```
    ** (EXIT) an exception was raised:
        ** (CaseClauseError) no case clause matching: 256
            (ex_abi 0.5.8) lib/abi/type_decoder.ex:292: ABI.TypeDecoder.decode_type/2
            (ex_abi 0.5.8) lib/abi/type_decoder.ex:336: anonymous fn/3 in ABI.TypeDecoder.decode_type/3
            (elixir 1.12.1) lib/enum.ex:2356: Enum."-reduce/3-lists^foldl/2-0-"/3
            (ex_abi 0.5.8) lib/abi/type_decoder.ex:331: ABI.TypeDecoder.decode_type/3
            (ex_abi 0.5.8) lib/abi/type_decoder.ex:188: anonymous fn/3 in ABI.TypeDecoder.do_decode_raw/2
            (elixir 1.12.1) lib/enum.ex:2356: Enum."-reduce/3-lists^foldl/2-0-"/3
            (ex_abi 0.5.8) lib/abi/type_decoder.ex:185: ABI.TypeDecoder.do_decode_raw/2
            (ex_abi 0.5.8) lib/abi/type_decoder.ex:179: ABI.TypeDecoder.decode_raw/2
            (exw3 0.6.1) lib/exw3/abi.ex:52: ExW3.Abi.decode_output/3
            (exw3 0.6.1) lib/exw3/contract.ex:214: ExW3.Contract.eth_call_helper/4
            (exw3 0.6.1) lib/exw3/contract.ex:480: ExW3.Contract.handle_call/3
            (stdlib 3.15) gen_server.erl:721: :gen_server.try_handle_call/4
            (stdlib 3.15) gen_server.erl:750: :gen_server.handle_msg/6
            (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

I checked the `ABI.TypeDecoder.decode_type` method and I see the following source:

```
  defp decode_type(:bool, data) do
    {encoded_value, rest} = decode_uint(data, 8)

    value =
      case encoded_value do
        1 -> true
        0 -> false
      end

    {value, rest}
  end
```

However it seems that for some reason the value it gets decodes to 256 and not 1 or 0. After more debugging I took a peek at the defp decode_type({:tuple, types}, data, full_data) function and added some inspects:

So, the decode_type({:tuple}) function receives the following data/full_data when the bool is true:

```
Data: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 243, 159, 214, 229, 26,
  173, ...>>
Full data: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 243, 159, 214, 229, 26,
  173, ...>>
```

Notice that there are 31 zeros before the last 1 so if this is decoded it will be *1*.

However, the `decode_type(:bool` function receives the following data:
```
Decode bool data: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 243, 159, 214, 229, 26,
  173, 136, ...>>
```

If you now cound the zeros before the one you'll cound 30 zeros so if this is to be decoded it will be decoded to 10 = *2*! Then for some reason I can't understand this is converted to 256!! Any idea why the data is garbled? 

Notice everything's working fine I I call the same method from ethers.js.

**Comment by ayrat555** [comment]
@spapas hello. can you please attach abi in json format and data that you want to encode/decode. 

most probably the issue is in exw3 library

**Comment by spapas** [comment]
Hello @ayrat555 yes it's possible that the problem is in exw3 ... 

The contract is this: https://github.com/spapas/voting/blob/master/contracts/Voter.sol - i'm attaching the abi in this message. 
[voter.zip](https://github.com/poanetwork/ex_abi/files/7821300/voter.zip)

The data that the `defp decode_type({:tuple, types}, data, full_data)` function receives is:

```
types: [:bool, :address, :string, :string, :string, :string, {:uint, 256}]
data: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 126, 127, 57, 229, 211,
  209, 59, 76, 230, 42, 234, 98, 23, 225, 5, 129, 210, 2, 48, 60, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  224, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 1, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 96, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 160, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 97, 221,
  102, 93, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 9, 81, 117, 101, 115, 116, 105, 111, 110, 63, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
  65, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 66, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 67, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0>>
```

Also please notice that if the bool is false it works fine; it only breaks if the bool is true!

**Comment by ayrat555** [comment]
@spapas just tried your example. it worked fine
```elixir
ABI.TypeDecoder.decode_raw(data, types)
[
  true,
  <<126, 127, 57, 229, 211, 209, 59, 76, 230, 42, 234, 98, 23, 225, 5, 129, 210,
    2, 48, 60>>,
  "Question?",
  "A",
  "B",
  "C",
  1641899613
]
```

**Comment by spapas** [comment]
Hello @ayrat555 I'm sorry I did a small mistake previously: Here's the types and data that the `decode_raw` receives: 

```
types: [tuple: [:bool, :address, :string, :string, :string, :string, {:uint, 256}]]
binary_data: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 126, 127, 57, 229, 211,
  209, 59, 76, 230, 42, 234, 98, 23, 225, 5, 129, 210, 2, 48, 60, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  224, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 1, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 96, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 160, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 97, 221,
  102, 93, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 9, 81, 117, 101, 115, 116, 105, 111, 110, 63, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
  65, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 66, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 67, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0>>
```

Then I can reproduce the problem:

```
iex(6)> ABI.TypeDecoder.decode_raw(data, types)
** (CaseClauseError) no case clause matching: 256
    (ex_abi 0.5.8) lib/abi/type_decoder.ex:297: ABI.TypeDecoder.decode_type/2
    (ex_abi 0.5.8) lib/abi/type_decoder.ex:345: anonymous fn/3 in ABI.TypeDecoder.decode_type/3
    (elixir 1.13.0) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_abi 0.5.8) lib/abi/type_decoder.ex:340: ABI.TypeDecoder.decode_type/3
    (ex_abi 0.5.8) lib/abi/type_decoder.ex:190: anonymous fn/3 in ABI.TypeDecoder.do_decode_raw/2
    (elixir 1.13.0) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_abi 0.5.8) lib/abi/type_decoder.ex:187: ABI.TypeDecoder.do_decode_raw/2
    (ex_abi 0.5.8) lib/abi/type_decoder.ex:181: ABI.TypeDecoder.decode_raw/2
```

**Comment by ayrat555** [comment]
@spapas try to parse the spec with `ABI.parse_specification`. it returns
```
  %ABI.FunctionSelector{
    function: "getVoteInfo",
    input_names: [],
    inputs_indexed: nil,
    method_id: <<37, 223, 249, 209>>,
    returns: [:bool, :address, :string, :string, :string, :string, {:uint, 256}],
    type: :function,
    types: []
  }
```

so the type `[tuple: [:bool, :address, :string, :string, :string, :string, {:uint, 256}]]` is not valid
